name: bank_clean_flutter
description: 金洁士

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  # Http请求库
  dio: ^3.0.8
  fluro: ^1.5.1
  fluttertoast: ^3.1.3
  # 适应
  flutter_screenutil: ^3.1.0
  # 状态管理
  provide: ^1.0.2
  # 储存
  shared_preferences: ^0.5.5
  # 颜色插件
  flutter_color_plugin: ^0.0.2
  # 手机权限
  permission_handler: ^4.4.0
  # 定位
  amap_location_fluttify: 0.8.11+481e45c
  # 数据加载中
  flutter_spinkit: ^4.0.0
  # picker 选择器
  flutter_cupertino_date_picker: ^1.0.26+2
  flutter_picker: ^1.1.0
  # 格式化日期
  date_format: ^1.0.8
  # 图片上传
  image_picker: ^0.6.3+4
  # 图片预览
  photo_view: ^0.9.2
  # 扫码
#  flutter_plugin_qrcode: ^1.0.3
  qrscan: ^0.2.17
  # 跳转
  url_launcher: ^5.1.1
  # 环形进度条
  percent_indicator: ^2.1.5
  # 多语言
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # 数据model层
  json_model: 0.0.2
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter:

  assets:
    - lib/images/icon-home.png
    - lib/images/icon-home-selected.png
    - lib/images/repair_address_icon.png
    - lib/images/floor_tabs.png
    - lib/images/floorBack_icon.png
    - lib/images/icon-log.png
    - lib/images/sel_up_icon.png
    - lib/images/sel_down_icon.png
    - lib/images/def_out_icon.png
    - lib/images/splash_logo.png
    - lib/images/sel_checked.png
    - lib/images/splash_bg.png
    - lib/images/icon-log-selected.png
    - lib/images/default_no_list.png
    - lib/images/call_phone_icon.png
    - lib/images/to_score_icon.png
    - lib/images/del_imge_icon.png
    - lib/images/icon-memb.png
    - lib/images/icon-memb-selected.png
    - lib/images/icon-mine.png
    - lib/images/icon-mine-selected.png
    - lib/images/icon-task.png
    - lib/images/icon-task-selected.png
    - lib/images/sel_picker.png
    - lib/images/login_logo.png
    - lib/images/phone_icon.png
    - lib/images/code_icon.png
    - lib/images/clean/clean_home_card_bg1.png
    - lib/images/clean/clean_home_card_bg2.png
    - lib/images/clean/clean_card_icon1.png
    - lib/images/clean/clean_card_icon2.png
    - lib/images/clean/location_icon.png
    - lib/images/clean/arrow_down.png
    - lib/images/clean/arrow_up.png
    - lib/images/clean/52.jpg
    - lib/images/clean/scan_code_icon.png
    - lib/images/clean/clock_in_icon.png
    - lib/images/clean/clock_in_icon2.png
    - lib/images/clean/close_icon.png
    - lib/images/clean/clock_pic.png
    - lib/images/clean/no_clean_feedback_list.png
    - lib/images/clean/feedback_address.png
    - lib/images/clean/sel_right.png
    - lib/images/clean/search_icon.png
    - lib/images/clean/phone_img.png
    - lib/images/clean/icon-plus.png
    - lib/images/clean/icon-minus.png
    - lib/images/clean/triangle_down.png
    - lib/images/my/my_page_bg.png
    - lib/images/my/right_icon.png
    - lib/images/my/work_icon.png
    - lib/images/my/materiel_icon.png
    - lib/images/my/check_work_icon.png
    - lib/images/my/repair_icon.png
    - lib/images/my/maintenance_inspection.png
    - lib/images/my/event_icon.png
    - lib/images/my/leave_icon.png
    - lib/images/check/home_icon.png
    - lib/images/check/home_icon_active.png
    - lib/images/check/check_box.png
    - lib/images/check/checked_box.png
    - lib/images/check/check_my_icon1.png
    - lib/images/check/check_my_icon2.png
    - lib/images/check/check_my_icon3.png
    - lib/images/check/check_my_icon4.png
    - lib/images/check/check_my_icon5.png
    - lib/images/check/check_my_icon6.png
    - lib/images/check/my_icon.png
    - lib/images/check/my_icon_active.png
    - lib/images/check/scheduling_icon.png
    - lib/images/check/scheduling_icon_active.png
    - lib/images/check/check_home_bg.png
    - lib/images/check/add_scheduling.png
    - lib/images/check/check_logo.png
    - lib/images/check/check_home_tab1.png
    - lib/images/check/check_home_tab2.png
    - lib/images/check/check_home_tab3.png
    - lib/images/check/check_home_tab4.png
    - lib/images/check/banner1.png
    - lib/images/check/check_tab1.png
    - lib/images/check/check_tab2.png
    - lib/images/check/check_right_icon.png
    - lib/images/check/check_icon.png
    - lib/images/check/checked_icon.png
    - lib/images/check/date1.png
    - lib/images/check/date2.png
    - lib/images/check/date3.png
    - lib/images/bank/assessment_icon_active.png
    - lib/images/bank/assessment_icon.png
    - lib/images/regionalManager/region_tab1.png
    - lib/images/regionalManager/region_tab2.png
    - lib/images/regionalManager/region_tab3.png
    - lib/images/regionalManager/region_apply_icon.png
    - lib/images/regionalManager/region_opinion.png
    - lib/images/bank/bank_home_card_bg2.png
    - lib/images/bank/bank_Scheduling.png
    - lib/images/projectManager/customer_opinion_icon.png
    - lib/images/projectManager/outlets_sel_icon.png
    - lib/images/projectManager/project_home_card_bg1.png
    - lib/images/projectManager/scrap_icon.png
    - lib/images/projectManager/project_card_icon1.png
    - lib/images/projectManager/project_home_card2.png
    - lib/images/projectManager/project_home_card_bg2.png
    - lib/images/projectManager/home_card1.png
    - lib/images/projectManager/home_card2.png
    - lib/images/projectManager/home_card3.png
    - lib/images/projectManager/home_card4.png
    - lib/images/projectManager/right_icon.png
    - lib/images/projectManager/project_home_bg.png
    - lib/images/projectManager/project_home_logo.png
    - lib/images/projectManager/project_sel_right.png
    - lib/images/projectManager/inventory_icon.png
    - lib/images/projectManager/normal_icon.png
    - lib/images/projectManager/abnormal_icon.png
    - lib/images/projectManager/not_counted_icon.png
    - lib/images/repairman/scan_code_icon.png
    - lib/images/repairman/scrap_icon.png

  uses-material-design: true


